<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [ 
                'code' => 'KE',
                'dial_code' => '+254',
                'name' => 'Kenya', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [ 
                'code' => 'UG',
                'dial_code' => '+256',
                'name' => 'Uganda', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
             [ 
                'code' => 'TZ',
                'dial_code' => '+255',
                'name' => 'Tanzania', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
             [ 
                'code' => 'RW',
                'dial_code' => '+250',
                'name' => 'Rwanda', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
             [ 
                'code' => 'SS',
                'dial_code' => '+211',
                'name' => 'South Sudan', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'ET',
                'dial_code' => '+251',
                'name' => 'Ethiopia', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'SO',
                'dial_code' => '+252',
                'name' => 'Somalia', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'BI',
                'dial_code' => '+257',
                'name' => 'Burundi', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'CD',
                'dial_code' => '+243',
                'name' => 'DR Congo', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
                [
                'code' => 'CG',
                'dial_code' => '+242',
                'name' => 'Republic of the Congo', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
                [
                'code' => 'CM',
                'dial_code' => '+237',
                'name' => 'Cameroon', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
                [
                'code' => 'GA',
                'dial_code' => '+241',
                'name' => 'Gabon', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
                [
                'code' => 'GQ',
                'dial_code' => '+240',
                'name' => 'Equatorial Guinea', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
                [
                'code' => 'ST',
                'dial_code' => '+239',
                'name' => 'Sao Tome and Principe', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'CV',
                'dial_code' => '+238',
                'name' => 'Cape Verde', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'US',
                'dial_code' => '+1',
                'name' => 'United States', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'GB',
                'dial_code' => '+44',
                'name' => 'United Kingdom', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'FR',
                'dial_code' => '+33',
                'name' => 'France', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'DE',
                'dial_code' => '+49',
                'name' => 'Germany', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'IT',
                'dial_code' => '+39',
                'name' => 'Italy', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'ES',
                'dial_code' => '+34',
                'name' => 'Spain', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'CN',
                'dial_code' => '+86',
                'name' => 'China', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
                [
                'code' => 'IN',
                'dial_code' => '+91',
                'name' => 'India', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
            [
                'code' => 'JP',
                'dial_code' => '+81',
                'name' => 'Japan', 
                'created_at' => now(),
                'created_by' => 1,
                'updated_at' => now(),
                'updated_by' => 1,
            ],
        ];
        
        foreach ($countries as $country) {
            Country::firstOrCreate($country);
        }
    }
}
