<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Expense Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
        .header-image { width: 100%; margin-bottom: 20px; }
        .header-image img { width: 100%; height: auto; display: block; }
    </style>
</head>
<body>
@php
        $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
        $headerImage = file_exists(public_path('header-01-landscape.jpeg')) ? public_path('header-01-landscape.jpeg') : null;
@endphp

<div class="header-image">
    @if($headerImage && file_exists($headerImage))
        <img src="data:image/jpeg;base64,{{ base64_encode(file_get_contents($headerImage)) }}" alt="Header Image">
    @endif
</div>

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                    <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                    <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif


                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Expense Report</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>
<div class="section">
    @if(isset($data['transactions']) && isset($data['totals']))
        <table class="table">
            <thead>
                <tr>
                    <th>Transaction #</th>
                    <th>Expense</th>
                    <th>Category</th>
                    <th>Cost Center</th>
                    <th>Amount</th>
                    <th>Tax</th>
                    <th>Net</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
            @forelse($data['transactions'] as $txn)
                <tr>
                    <td><strong>{{ $txn['id'] ?? '' }}</strong></td>
                    <td>{{ $txn['expense'] ?? '' }}</td>
                    <td>{{ $txn['category'] ?? '' }}</td>
                    <td>{{ $txn['cost_center'] ?? '' }}</td>
                    <td><strong>{{ number_format((float) ($txn['amount'] ?? 0), 2) }}</strong></td>
                    <td>{{ number_format((float) ($txn['tax_amount'] ?? 0), 2) }}</td>
                    <td><strong>{{ number_format((float) ($txn['net_amount'] ?? 0), 2) }}</strong></td>
                    <td>{{ !empty($txn['created_at']) ? (is_string($txn['created_at']) ? date('d M Y', strtotime($txn['created_at'])) : (\Illuminate\Support\Carbon::parse($txn['created_at'])->format('d/m/Y'))) : '' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align:center;color:#dc2626;">No expense entries found.</td>
                </tr>
            @endforelse
            <!-- Totals row -->
            <tr style="background-color:#e0e7ff;font-weight:bold;">
                <td colspan="4" style="text-align:right;">Totals:</td>
                <td>{{ number_format((float) $data['totals']['total'], 2) }}</td>
                <td>{{ number_format((float) $data['totals']['taxes'], 2) }}</td>
                <td>{{ number_format((float) $data['totals']['net'], 2) }}</td>
                <td></td>
            </tr>
            </tbody>
        </table>
        <!-- Totals summary below table removed to avoid duplication -->
    @else
        <div style="color:#dc2626;font-weight:bold;font-size:16px;">No expense data available for this report.</div>
    @endif
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>