<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Expenses Payment Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
        .header-image { width: 100%; margin-bottom: 20px; }
        .header-image img { width: 100%; height: auto; display: block; }
    </style>
</head>
<body>
@php
        $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
        $headerImage = file_exists(public_path('header-01-landscape.jpeg')) ? public_path('header-01-landscape.jpeg') : null;
@endphp

<div class="header-image">
    @if($headerImage && file_exists($headerImage))
        <img src="data:image/jpeg;base64,{{ base64_encode(file_get_contents($headerImage)) }}" alt="Header Image">
    @endif
</div>

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                    <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                    <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif


                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Expenses Payment Report</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>
<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Cost Center</th>
                <th>Source Account</th>
                <th>Status</th>
                <th>Transaction #</th>
                <th>Amount</th>
                <th>Narration</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data['payments'] as $payment)
            <tr>
                <td>{{ optional($payment['created_at'])->format('Y-m-d') }}</td>
                <td>{{ $payment['category_name'] ?? '-' }}</td>
                <td>{{ $payment['cost_center_name'] ?? '-' }}</td>
                <td>{{ $payment['source_account_name'] ?? '-' }}</td>
                <td>{{ $payment['expense_status'] ?? '-' }}</td>
                <td>{{ $payment['transaction_number'] ?? '-' }}</td>
                <td><strong>{{ number_format((float) ($payment['amount'] ?? 0), 2) }}</strong></td>
                <td>{{ $payment['narration'] ?? '-' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @if(isset($data['totals']))
        <div class="section">
            <span style="font-size:14px;font-weight:bold;">Total Amount:</span>
            <strong>{{ number_format((float) ($data['totals']['total'] ?? 0), 2) }}</strong><br>
        </div>
    @endif
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
