<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoices Report - Customer</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
        $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
@endphp

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                    <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                    <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif


                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Invoices Report - Customer</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>
<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Job Reference ID</th>
                <th>Customer</th>
                <th>Invoice #</th>
                <th>Project Name</th>
                <th>Currency</th>
                <th>Amount</th>
                <th>Paid</th>
                <th>Balance</th>
                <th>Status</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data['invoices'] as $invoice)
            <tr>
                <td>
                    @php
                        $dateValue = $invoice['date'] ?? $invoice['created_at'] ?? null;
                    @endphp
                    @if($dateValue)
                        {{ \Carbon\Carbon::parse($dateValue)->format('d/m/Y') }}
                    @else
                        -
                    @endif
                </td>
                <td>{{ $invoice['job_reference_id'] ?? '-' }}</td>
                <td>{{ $invoice['customer'] ?? '-' }}</td>
                <td>{{ $invoice['invoice_number'] ?? '-' }}</td>
                <td>{{ $invoice['project_name'] ?? '-' }}</td>
                <td>{{ $invoice['currency'] ?? '-' }}</td>
                <td>{{ number_format((float) ($invoice['amount'] ?? 0), 2) }}</td>
                <td>{{ number_format((float) ($invoice['paid'] ?? 0), 2) }}</td>
                <td>{{ number_format((float) ($invoice['balance'] ?? 0), 2) }}</td>
                <td>{{ $invoice['status'] ?? '-' }}</td>
                <td>{{ $invoice['created_by_name'] ?? '-' }}</td>
            </tr>
        @endforeach
        @if(isset($data['totals']))
            <tr>
                <td><strong>Totals:</strong></td>
                <td colspan="5"></td>
                <td><strong>{{ number_format((float) ($data['totals']['amount'] ?? 0), 2) }}</strong></td>
                <td><strong>{{ number_format((float) ($data['totals']['total_paid'] ?? 0), 2) }}</strong></td>
                <td><strong>{{ number_format((float) ($data['totals']['total_balance'] ?? 0), 2) }}</strong></td>
                <td></td>
                <td></td>
            </tr>
        @endif
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
