<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice Payments Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
    $logoPath = public_path('logo.png');
    $logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : null;
@endphp

<div class="header">
    <div class="logo">
        @if($logoData)
            <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
        @else
            <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
        @endif
    </div>
    <div style="text-align: right;">
        <h1>Invoice Payments Report</h1>
        <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
    </div>
</div>

<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Payment #</th>
                <th>Invoice #</th>
                <th>Amount</th>
                <th>Tax</th>
                <th>Net</th>
                <th>Currency</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data['payments'] as $payment)
            <tr>
                <td><strong>{{ $payment->id }}</strong></td>
                <td><strong>{{ $payment->invoice_number }}</strong></td>
                <td><strong>{{ number_format((float) $payment->amount, 2) }}</strong></td>
                <td>{{ number_format((float) $payment->tax_amount, 2) }}</td>
                <td><strong>{{ number_format((float) $payment->net_amount, 2) }}</strong></td>
                <td>{{ $payment->currency }}</td>
                <td>{{ optional($payment->created_at)->format('d M Y') }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="section">
        <span style="font-size:14px;font-weight:bold;color:#1d4ed8;">Total:</span> <strong>{{ number_format((float) $data['totals']['total'], 2) }}</strong><br>
        <span style="font-size:14px;font-weight:bold;color:#1d4ed8;">Taxes:</span> <strong>{{ number_format((float) $data['totals']['taxes'], 2) }}</strong><br>
        <span style="font-size:14px;font-weight:bold;color:#1d4ed8;">Net:</span> <strong>{{ number_format((float) $data['totals']['net'], 2) }}</strong>
    </div>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>