<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice Payments Company Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
        .header-image { width: 100%; margin-bottom: 20px; }
        .header-image img { width: 100%; height: auto; display: block; }
    </style>
</head>
<body>
@php
        $headerImage = file_exists(public_path('header-01-landscape.jpeg')) ? public_path('header-01-landscape.jpeg') : null;
@endphp

<div class="header-image">
    @if($headerImage && file_exists($headerImage))
        <img src="data:image/jpeg;base64,{{ base64_encode(file_get_contents($headerImage)) }}" alt="Header Image">
    @endif
</div>

<div class="header">
    <div style="text-align: right;">
        <h1>Invoice Payments Company Report</h1>
        <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
    </div>
</div>
<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Date</th>
                <th>Company</th>
                <th>Job Reference ID</th>
                <th>Invoice #</th>
                <th>Currency</th>
                <th>Amount</th>
                <th>Transacted By</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data['payments'] as $payment)
            <tr>
                <td><strong>{{ $payment->id }}</strong></td>
                <td>{{ optional($payment->created_at)->format('d/m/Y') }}</td>
                <td>{{ $payment->company_name ?? '-' }}</td>
                <td>{{ $payment->job_reference_id ?? '-' }}</td>
                <td>{{ $payment->invoice_number ?? '-' }}</td>
                <td>{{ $payment->currency ?? '-' }}</td>
                <td><strong>{{ number_format((float) ($payment->amount ?? 0), 2) }}</strong></td>
                <td>{{ $payment->transacted_by_name ?? '-' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    @if(isset($data['totals']))
        <div class="section">
            <span style="font-size:14px;font-weight:bold;">Total Amount:</span>
            <strong>{{ number_format((float) ($data['totals']['total'] ?? 0), 2) }}</strong><br>
        </div>
    @endif
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
