<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Margin Per Project Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
        $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
@endphp

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                    <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                    <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif


                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Margin Per Project Report</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>
<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Job Reference ID</th>
                <th>Customer</th>
                <th>Project Name</th>
                <th>Revenue ({{ $filters['currency_code'] ?? '' }})</th>
                <th>Cost ({{ $filters['currency_code'] ?? '' }})</th>
                <th>Margin ({{ $filters['currency_code'] ?? '' }})</th>
            </tr>
        </thead>
        <tbody>
        @php
            $rows = $data['rows'] ?? $data;
            $totals = $data['totals'] ?? null;
        @endphp
        @foreach($rows as $row)
            <tr>
                <td>{{ \Carbon\Carbon::parse($row['date'] ?? '')->format('d/m/Y') }}</td>
                <td>{{ $row['job_reference_id'] ?? '' }}</td>
                <td>{{ $row['customer'] ?? '' }}</td>
                <td>{{ $row['project_name'] ?? '' }}</td>
                <td>{{ number_format((float) ($row['revenue'] ?? 0), 2) }}</td>
                <td>{{ number_format((float) ($row['cost'] ?? 0), 2) }}</td>
                <td>{{ number_format((float) ($row['margin'] ?? 0), 2) }}</td>
            </tr>
        @endforeach
        @if($totals)
            <tr>
                <td colspan="4" style="font-weight: 600;">Totals</td>
                <td>{{ number_format((float) ($totals['revenue'] ?? 0), 2) }}</td>
                <td>{{ number_format((float) ($totals['cost'] ?? 0), 2) }}</td>
                <td>{{ number_format((float) ($totals['margin'] ?? 0), 2) }}</td>
            </tr>
        @endif
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>