<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Orders Summary Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto;}
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
    $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
@endphp

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                        <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                        <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif
                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Orders Summary Report</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>

<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Job Ref</th>
                <th>Customer</th>
                <th>Title</th>
                <th>Currency</th>
                <th>Total Amount</th>
                <th>Status</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data as $order)
            <tr>
                <td>
                    @if(!empty($order['created_at']))
                        {{ \Carbon\Carbon::parse($order['created_at'])->format('M d, Y h:i A') }}
                    @endif
                </td>
                <td>{{ $order['job_reference_id'] ?? '' }}</td>
                <td>{{ $order['customer_name'] ?? '' }}</td>
                <td>{{ $order['title'] ?? '' }}</td>
                <td>{{ $order['currency'] ?? '' }}</td>
                <td><strong>{{ isset($order['total_amount']) ? number_format((float) $order['total_amount'], 2) : '' }}</strong></td>
                <td>{{ $order['status'] ?? '' }}</td>
                <td>{{ $order['created_by_name'] ?? '' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
