<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Orders Summary Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
    $logoPath = public_path('logo.png');
    $logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : null;
@endphp

<div class="header">
    <div class="logo">
        @if($logoData)
            <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
        @else
            <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
        @endif
    </div>
    <div style="text-align: right;">
        <h1>Orders Summary Report</h1>
        <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
    </div>
</div>

<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Order #</th>
                <th>Project</th>
                <th>Customer</th>
                <th>Job Ref</th>
                <th>Quotation</th>
                <th>Title</th>
                <th>Status</th>
                <th>Total Amount</th>
                <th>Currency</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data as $order)
            <tr>
                <td><strong>{{ $order['order_number'] ?? '' }}</strong></td>
                <td>
                    @if(isset($order['project']))
                        @if(is_array($order['project']) && isset($order['project']['name']))
                            {{ $order['project']['name'] }}
                        @elseif(is_object($order['project']) && isset($order['project']->name))
                            {{ $order['project']->name }}
                        @else
                            {{ $order['project'] }}
                        @endif
                    @endif
                </td>
                <td>{{ $order['customer_name'] ?? '' }}</td>
                <td>{{ $order['job_reference_id'] ?? '' }}</td>
                <td>{{ $order['quotation_title'] ?? '' }}</td>
                <td>{{ $order['title'] ?? '' }}</td>
                <td>{{ $order['status'] ?? '' }}</td>
                <td><strong>{{ isset($order['total_amount']) ? number_format((float) $order['total_amount'], 2) : '' }}</strong></td>
                <td>{{ $order['currency'] ?? '' }}</td>
                <td>
                    @if(!empty($order['created_at']))
                        {{ \Carbon\Carbon::parse($order['created_at'])->format('M d, Y h:i A') }}
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
