<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projects Summary Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
    $logoPath = public_path('logo.png');
    $logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : null;
@endphp

<div class="header">
    <div class="logo">
        @if($logoData)
            <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
        @else
            <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
        @endif
    </div>
    <div style="text-align: right;">
        <h1>Projects Summary Report</h1>
        <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
    </div>
</div>

<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Project #</th>
                <th>Name</th>
                <th>Customer</th>
                <th>Category</th>
                <th>Status</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Currency</th>
                <th>Assigned Companies</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data as $project)
            <tr>
                <td><strong>{{ $project['id'] }}</strong></td>
                <td><strong>{{ $project['name'] }}</strong></td>
                <td>{{ $project['customer_name'] ?? '-' }}</td>
                <td>{{ $project['project_category'] ?? '-' }}</td>
                <td>{{ $project['status'] ?? '-' }}</td>
                <td>{{ $project['start_date'] ? \Carbon\Carbon::parse($project['start_date'])->format('d M Y') : '-' }}</td>
                <td>{{ $project['end_date'] ? \Carbon\Carbon::parse($project['end_date'])->format('d M Y') : '-' }}</td>
                <td>{{ $project['currency'] ?? '-' }}</td>
                <td>
                    @if(isset($project['assigned_companies']) && is_array($project['assigned_companies']) && count($project['assigned_companies']))
                        @foreach($project['assigned_companies'] as $company)
                            <span><strong>{{ $company['name'] }}</strong></span>@if(!$loop->last), @endif
                        @endforeach
                    @else
                        -
                    @endif
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
