<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projects Summary Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
        $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
@endphp

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                    <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                    <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif


                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Projects Summary Report</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>
<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Job Ref</th>
                <th>Customer</th>
                <th>Project Name</th>
                <th>Category</th>
                <th>Source Origin</th>
                <th>Location</th>
                <th>Project Owner</th>
                <th>Currency</th>
                <th>Amount</th>
                <th>Created By</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data as $project)
            <tr>
                <td>
                    @if(!empty($project['start_date']))
                        {{ \Carbon\Carbon::parse($project['start_date'])->format('d/m/Y') }}
                    @else
                        -
                    @endif
                </td>
                <td>{{ $project['job_reference_id'] ?? '-' }}</td>
                <td>{{ $project['customer_name'] ?? '-' }}</td>
                <td><strong>{{ $project['name'] ?? '-' }}</strong></td>
                <td>{{ $project['project_category'] ?? '-' }}</td>
                <td>{{ $project['project_source_origin'] ?? '-' }}</td>
                <td>{{ $project['project_location'] ?? '-' }}</td>
                <td>{{ $project['project_owner'] ?? '-' }}</td>
                <td>{{ $project['currency'] ?? '-' }}</td>
                <td>
                    @if(isset($project['budget_estimate']))
                        {{ number_format((float) $project['budget_estimate'], 2) }}
                    @else
                        -
                    @endif
                </td>
                <td>{{ $project['created_by_name'] ?? '-' }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>
