<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Revenue Snapshot Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .card { border: 1px solid #e5e7eb; border-radius: 6px; padding: 10px 12px; margin-bottom: 12px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>
@php
    $logoPath = public_path('logo.png');
    $logoData = file_exists($logoPath) ? base64_encode(file_get_contents($logoPath)) : null;
@endphp

<div class="header">
    <div class="logo">
        @if($logoData)
            <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
        @else
            <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
        @endif
    </div>
    <div style="text-align: right;">
        <h1>Revenue Snapshot Report</h1>
        <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
    </div>
</div>

<div class="section card">
    <table style="width:100%; border-collapse:collapse;">
        <thead>
            <tr style="background:#f3f4f6;">
                <th style="border:1px solid #e5e7eb; padding:8px; text-align:left;">Total Payments Received</th>
                <th style="border:1px solid #e5e7eb; padding:8px; text-align:left;">Total Refunds</th>
                <th style="border:1px solid #e5e7eb; padding:8px; text-align:left;">Total Invoices Issued</th>
                <th style="border:1px solid #e5e7eb; padding:8px; text-align:left;">Outstanding Invoices</th>
                <th style="border:1px solid #e5e7eb; padding:8px; text-align:left;">Currency</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td style="border:1px solid #e5e7eb; padding:8px;">{{ number_format($data['total_payments_received'] ?? 0, 2) }}</td>
                <td style="border:1px solid #e5e7eb; padding:8px;">{{ number_format($data['total_refunds'] ?? 0, 2) }}</td>
                <td style="border:1px solid #e5e7eb; padding:8px;">{{ number_format($data['total_invoices_issued'] ?? 0, 2) }}</td>
                <td style="border:1px solid #e5e7eb; padding:8px;">{{ number_format($data['outstanding_invoices'] ?? 0, 2) }}</td>
                <td style="border:1px solid #e5e7eb; padding:8px;">{{ $data['currency'] ?? '' }}</td>
            </tr>
        </tbody>
    </table>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>