<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tax Payments (Customer) Report</title>
    <style>
        @page { margin: 40px 40px 60px 40px; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }
        .logo img { height: 40px; width: auto; }
        .brand-name { font-size: 18px; font-weight: 700; color: #111827; }
        .muted { color: #6b7280; }
        h1 { font-size: 20px; margin: 0 0 4px 0; }
        .section { margin-bottom: 16px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .table th, .table td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        .table th { background-color: #f3f4f6; font-weight: 600; }
        .magic-table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        .footer { position: fixed; bottom: 20px; left: 40px; right: 40px; font-size: 10px; color: #9ca3af; text-align: center; }
        .header-image { width: 100%; margin-bottom: 20px; }
        .header-image img { width: 100%; height: auto; display: block; }
    </style>
</head>
<body>
@php
        $logoData = file_exists($instanceLogo) ? base64_encode(file_get_contents($instanceLogo)) : null;
        $headerImage = file_exists(public_path('header-01-landscape.jpeg')) ? public_path('header-01-landscape.jpeg') : null;
@endphp

<div class="header-image">
    @if($headerImage && file_exists($headerImage))
        <img src="data:image/jpeg;base64,{{ base64_encode(file_get_contents($headerImage)) }}" alt="Header Image">
    @endif
</div>

<div class="header">
    <table class="magic-table">
        <tr>
            <td style="width: 50%; vertical-align: top; padding-right: 8px;">
                <div class="logo">
                    @if($logoData)
                    <img src="data:image/png;base64,{{ $logoData }}" alt="Company Logo">
                    @else
                    <div class="brand-name">{{ $senderName ?? 'Company' }}</div>
                    @endif


                </div>
            </td>
            <td style="width: 50%; vertical-align: top; text-align: right;">
                <h1>Tax Payments (Customer) Report</h1>
                <div class="muted">Generated on {{ $generatedAt->format('d M Y H:i') }}</div>
            </td>
        </tr>
    </table>
</div>
<div class="section">
    <table class="table">
        <thead>
            <tr>
                <th>Transaction #</th>
                <th>Customer</th>
                <th>Invoice #</th>
                <th>Amount</th>
                <th>Tax</th>
                <th>Net</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        @foreach($data['transactions'] as $txn)
            <tr>
                <td><strong>{{ $txn->id }}</strong></td>
                <td>{{ $txn->customer_name }}</td>
                <td><strong>{{ $txn->invoice_number }}</strong></td>
                <td><strong>{{ number_format((float) $txn->amount, 2) }}</strong></td>
                <td>{{ number_format((float) $txn->tax_amount, 2) }}</td>
                <td><strong>{{ number_format((float) $txn->net_amount, 2) }}</strong></td>
                <td>{{ optional($txn->created_at)->format('d/m/Y') }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
    <div class="section">
        <span style="font-size:14px;font-weight:bold;color:#1d4ed8;">Taxes:</span> <strong>{{ number_format((float) $data['totals']['taxes'], 2) }}</strong><br>
        <span style="font-size:14px;font-weight:bold;color:#1d4ed8;">Converted Taxes:</span> <strong>{{ number_format((float) $data['totals']['converted_taxes'], 2) }}</strong><br>
    </div>
</div>

<div class="footer">
    Generated by {{ $senderName ?? 'Company' }} &middot; {{ $senderEmail ?? '' }}
</div>
</body>
</html>